Fix: Improve path handling
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -8,6 +8,7 @@ description: "Replaces/updates the Python project metadata/version string"
 # Note: works with both pyproject.toml and setup.py
 
 inputs:
+  # Mandatory
   REPLACEMENT_VERSION:
     description: "New project version string"
     required: true
@@ -16,22 +17,40 @@ inputs:
     description: "Directory location containing project code"
     type: string
     required: false
-    default: ""
 
 runs:
   using: "composite"
   steps:
+    - name: "Setup action/environment"
+      shell: bash
+      run: |
+        # Setup action/environment
+        # Handle path_prefix input consistently and when absent
+        path_prefix="${{ inputs.PATH_PREFIX }}"
+        if [ -z "$path_prefix" ]; then
+          # Set current directory as path prefix
+          path_prefix="."
+        else
+          # Strip any trailing slash in provided path
+          path_prefix="${path_prefix%/}"
+        fi
+        # Verify is a valid directory path
+        if [ ! -d "$path_prefix" ]; then
+          echo "Error: invalid path/prefix to project directory ❌"; exit 1
+        fi
+        echo "path_prefix=$path_prefix" >> "$GITHUB_ENV"
+
     # yamllint disable-line rule:line-length
     - uses: lfreleng-actions/path-check-action@7f728b8ac404d3309cfa576f0ffc54217ade2faa # v0.1.1
       id: setup-py
       with:
-        path: "${{ inputs.path_prefix }}setup.py"
+        path: "${{ env.path_prefix }}/setup.py"
 
     # yamllint disable-line rule:line-length
     - uses: lfreleng-actions/path-check-action@7f728b8ac404d3309cfa576f0ffc54217ade2faa # v0.1.1
       id: pyproject-toml
       with:
-        path: "${{ inputs.path_prefix }}pyproject.toml"
+        path: "${{ env.path_prefix }}/pyproject.toml"
 
     - name: "Patch Python project version: setup.py"
       id: patch-version-setup-py
@@ -41,7 +60,7 @@ runs:
       with:
         flags: "-i -E"
         regex: 's:version=.*$:version="${{ inputs.REPLACEMENT_VERSION }}":'
-        path: "${{ inputs.path_prefix }}setup.py"
+        path: "${{ env.path_prefix }}/setup.py"
 
     - name: "Patch Python project version: pyproject.toml"
       id: patch-version-pyproject-toml
@@ -51,4 +70,4 @@ runs:
       with:
         flags: "-i -E"
         regex: 's:^version =.*$:version = "${{ inputs.REPLACEMENT_VERSION }}":'
-        path: "${{ inputs.path_prefix }}pyproject.toml"
+        path: "${{ env.path_prefix }}/pyproject.toml"
