Fix: Send complex instruction to sed action to set exit status
Sed doesn't set exit status when stream manipulation performs no
string substitutions. This has to be explicitly set.

Also includes:
- Formatting updates, fix input capitalisation, string quoting
- Aligns path_prefix handling with the other actions

Signed-off-by: Matthew Watkins <matt@modeseven.org>

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -3,39 +3,69 @@
 # SPDX-FileCopyrightText: 2025 The Linux Foundation
 
 # Action test/validation workflow
-name: "Test GitHub Action 🧪"
+name: 'Test GitHub Action 🧪'
 
 # yamllint disable-line rule:truthy
 on:
   workflow_dispatch:
   push:
-    branches: ["main"]
+    branches: ['main']
   pull_request:
-    branches: ["main"]
+    branches: ['main']
 
 permissions: {}
 
 jobs:
   ### Test the GitHub Action in this Repository ###
   tests:
-    name: "Action Testing"
-    runs-on: ubuntu-24.04
+    name: 'Action Testing'
+    runs-on: 'ubuntu-latest'
     permissions:
       contents: read
+    timeout-minutes: 5
     steps:
-      - name: "Checkout repository"
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: 'Checkout repository'
+        # yamllint disable-line rule:line-length
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
 
       # Perform setup prior to running test(s)
-      - name: "Checkout sample project repository"
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: 'Checkout sample repository [test-python-project]'
+        # yamllint disable-line rule:line-length
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
         with:
-          repository: "lfreleng-actions/test-python-project"
-          path: "test-python-project"
+          repository: 'lfreleng-actions/test-python-project'
+          path: 'test-python-project'
 
-      - name: "Run Action: ${{ github.repository }}"
+      - name: "Run Action: ${{ github.repository }} [test-python-project]]"
         uses: ./
         with:
-          path_prefix: "test-python-project/"
+          path_prefix: 'test-python-project'
           # Python projects do not have a "v" prefix
-          replacement_version: "0.2.0"
+          replacement_version: '0.2.0'
+
+      # Perform setup prior to running test(s)
+      - name: 'Checkout sample repository [lftools]'
+        # yamllint disable-line rule:line-length
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
+        with:
+          repository: 'lfit/releng-lftools'
+          path: 'releng-lftools'
+
+      # lftools uses dynamic versioning, so this action will fail
+      - name: "Run Action: ${{ github.repository }} [lftools]]"
+        uses: ./
+        id: 'failure'
+        continue-on-error: true
+        with:
+          path_prefix: 'releng-lftools'
+          # Python projects do not have a "v" prefix
+          replacement_version: '0.2.0'
+
+      - name: 'Error if step above did NOT fail'
+        if: steps.failure.outcome == 'success'
+        shell: bash
+        run: |
+          # Error if step above did NOT fail
+          echo 'Error: previous test step did NOT fail ❌'
+          cat pyproject.toml setup.py || true
+          exit 1
